version: 2
jobs:
  install-dependencies: 
    docker:
      - image: node:11.10.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  build_deploy:
    docker:
      - image: node:11.10.1
    
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: 
          name: build
          command: yarn build
      - run:
          name: deploy
          command: yarn netlify:deploy    

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - install-dependencies:
        filters:
          branches:
            only: /^(develop|master)$/
          tags:
            only: /.*/
    - build_deploy:
        requires: 
        - install-dependencies
        filters:
          branches: 
            ignore: /.*/
          tags:
            only: /^v([0-9]+).([0-9]+).([0-9]+)$/
